dirtyInputs: true
id: 'JOB - Store Playbook Metrics in Dataset'
inputs: []
name: JOB - Store Playbook Metrics in Dataset
outputs: []
starttaskid: "0"
tags:
- SOC_Framework
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 1d9a14ec-7271-4242-888f-02cb1d17d0ff
      iscommand: false
      name: ""
      version: -1
    taskid: 1d9a14ec-7271-4242-888f-02cb1d17d0ff
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 195.25,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: errorPath
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "4"
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      fromdate:
        simple: 2 days ago
      limit:
        simple: "500"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Searches Demisto alerts. A summarized version of this scrips is available with the summarizedversion argument.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs-cortex.paloaltonetworks.com/r/Cortex-XSIAM/Cortex-XSIAM-Administrator-Guide/Permission-Management
      id: b04efe4c-cc35-4832-a4b9-8376d17c5da2
      iscommand: false
      name: Search Alerts
      script: SearchAlertsV2
      type: regular
      version: -1
    taskid: b04efe4c-cc35-4832-a4b9-8376d17c5da2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 195.25,
          "y": 210
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      forEach: true
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      Alert:
        simple: ${foundIncidents}
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 9ca61b9d-868c-4a3f-836c-d504bee3e4b3
      iscommand: false
      name: Get Alert Tasks and Store to Dataset
      playbookId: 'Get Alert Tasks and Store to Dataset'
      type: playbook
      version: -1
    taskid: 9ca61b9d-868c-4a3f-836c-d504bee3e4b3
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 380
        }
      }
  "3":
    continueonerror: true
    continueonerrortype: errorPath
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "4"
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: e8725c45-643e-4c8b-ae39-f3142bf4ab74
      iscommand: true
      name: Close Investigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: e8725c45-643e-4c8b-ae39-f3142bf4ab74
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 550
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 883522e7-a731-48a1-88c9-867c76786028
      iscommand: false
      name: Foundation - Error Handling
      playbookId: 'Foundation - Error Handling'
      type: playbook
      version: -1
    taskid: 883522e7-a731-48a1-88c9-867c76786028
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 390.5,
          "y": 720
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 6147a2a8-51fd-4eb7-99e2-c8821a6974d7
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 6147a2a8-51fd-4eb7-99e2-c8821a6974d7
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 245.25,
          "y": 890
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 900,
        "width": 721.5,
        "x": 50,
        "y": 50
      }
    }
  }
