dirtyInputs: true
id: JOB - Triage Incidents
inputs: []
name: JOB - Triage Incidents
outputs: []
quiet: true
starttaskid: "0"
tags:
- SOC_Framework
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ef0db9e6-cb66-4744-8ec1-d010d2a2bb25
      iscommand: false
      name: ""
      version: -1
    taskid: ef0db9e6-cb66-4744-8ec1-d010d2a2bb25
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 290.5,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: errorPath
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "6"
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      body:
        simple: '{"request_data" : {"filters" : [{"field": "status","operator": "eq","value":
          "New"},{"operator": "lte", "value": ${TimeNowUnix}, "field": "modification_time"},{"operator":
          "eq", "value": "false", "field": "starred"}]}}'
      extend-context:
        simple: Found=.
      uri:
        simple: /public_api/v1/incidents/get_incidents
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: send HTTP POST request.
      id: a1f20685-0409-47e8-a448-5fda388e52a5
      iscommand: true
      name: Get Incidents
      script: '|||core-api-post'
      type: regular
      version: -1
    taskid: a1f20685-0409-47e8-a448-5fda388e52a5
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 481,
          "y": 380
        }
      }
  "3":
    continueonerror: true
    continueonerrortype: errorPath
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "6"
      '#none#':
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      hoursAgo:
        simple: "6"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Retrieves the current date and time.
      id: 6495cad3-f3c5-4f28-ad98-88e140343b78
      iscommand: false
      name: Get Time
      script: GetTime
      type: regular
      version: -1
    taskid: 6495cad3-f3c5-4f28-ad98-88e140343b78
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 290.5,
          "y": 210
        }
      }
  "5":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Found.response.reply.incidents.incident_id
          operator: isExists
          right:
            value: {}
      label: "yes"
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "7"
      "yes":
      - "8"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 1363bdca-3f21-4360-a321-edb50c4ae20c
      iscommand: false
      name: Incidents to Triage?
      type: condition
      version: -1
    taskid: 1363bdca-3f21-4360-a321-edb50c4ae20c
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 531,
          "y": 550
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 6022cef1-efad-4af2-8e12-42885fb4ae9b
      iscommand: false
      name: Foundation - Error Handling
      playbookId: Foundation - Error Handling
      type: playbook
      version: -1
    taskid: 6022cef1-efad-4af2-8e12-42885fb4ae9b
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 550
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: bd5e247a-beca-412e-8766-a3bdc0a9ff8d
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: bd5e247a-beca-412e-8766-a3bdc0a9ff8d
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 340.5,
          "y": 890
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      forEach: true
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      incident_id:
        simple: ${Found.response.reply.incidents.incident_id}
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 1827d8d0-9892-4fc5-a9b4-2562ad38630d
      iscommand: false
      name: Close Incidents
      playbookId: 97f87182-252c-454b-810d-c951e39abe9d
      type: playbook
      version: -1
    taskid: 1827d8d0-9892-4fc5-a9b4-2562ad38630d
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 676.25,
          "y": 720
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 900,
        "width": 1007.25,
        "x": 50,
        "y": 50
      }
    }
  }
