id: JOB - Store Playbook Metrics in Dataset
version: 7
vcShouldKeepItemLegacyProdMachine: false
name: JOB - Store Playbook Metrics in Dataset
tags:
- SOC_Framework
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 1d9a14ec-7271-4242-888f-02cb1d17d0ff
    type: start
    task:
      id: 1d9a14ec-7271-4242-888f-02cb1d17d0ff
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 195.25,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 2c6af60f-fbec-426b-b32f-40fcb3d57b6f
    type: regular
    task:
      id: 2c6af60f-fbec-426b-b32f-40fcb3d57b6f
      version: -1
      name: Search Alerts
      description: |-
        Searches Demisto alerts. A summarized version of this scrips is available with the summarizedversion argument.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs-cortex.paloaltonetworks.com/r/Cortex-XSIAM/Cortex-XSIAM-Administrator-Guide/Permission-Management
      scriptName: SearchAlertsV2
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#error#':
      - "4"
      '#none#':
      - "6"
    scriptarguments:
      fromdate:
        simple: 1 hour ago
      limit:
        simple: "500"
    separatecontext: false
    continueonerror: true
    continueonerrortype: errorPath
    view: |-
      {
        "position": {
          "x": 195.25,
          "y": 210
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: e8725c45-643e-4c8b-ae39-f3142bf4ab74
    type: regular
    task:
      id: e8725c45-643e-4c8b-ae39-f3142bf4ab74
      version: -1
      name: Close Investigation
      description: commands.local.cmd.close.inv
      script: Builtin|||closeInvestigation
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#error#':
      - "4"
      '#none#':
      - "5"
    separatecontext: false
    continueonerror: true
    continueonerrortype: errorPath
    view: |-
      {
        "position": {
          "x": 340.5,
          "y": 550
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 883522e7-a731-48a1-88c9-867c76786028
    type: playbook
    task:
      id: 883522e7-a731-48a1-88c9-867c76786028
      version: -1
      name: Foundation - Error Handling
      playbookName: Foundation - Error Handling
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    separatecontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 6147a2a8-51fd-4eb7-99e2-c8821a6974d7
    type: title
    task:
      id: 6147a2a8-51fd-4eb7-99e2-c8821a6974d7
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 195.25,
          "y": 890
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: d75f37fe-5e32-4865-8e29-29060b3cc3e4
    type: playbook
    task:
      id: d75f37fe-5e32-4865-8e29-29060b3cc3e4
      version: -1
      name: Get Alert Tasks and Store to Dataset
      playbookName: Get Alert Tasks and Store to Dataset
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    separatecontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 340.5,
          "y": 380
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 900,
        "width": 671.5,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
quiet: true
dirtyInputs: true
