id: JOB - Store Playbook Metrics in Dataset
version: 2
vcShouldKeepItemLegacyProdMachine: false
name: JOB - Store Playbook Metrics in Dataset
tags:
- SOC_Framework
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 70ae04ac-deed-4719-8f9a-d689a1125612
    type: start
    task:
      id: 70ae04ac-deed-4719-8f9a-d689a1125612
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 195.25,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: f90525f7-68cd-481f-8362-10dea2acebb7
    type: regular
    task:
      id: f90525f7-68cd-481f-8362-10dea2acebb7
      version: -1
      name: Search Alerts
      description: |-
        Searches Demisto alerts. A summarized version of this scrips is available with the summarizedversion argument.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs-cortex.paloaltonetworks.com/r/Cortex-XSIAM/Cortex-XSIAM-Administrator-Guide/Permission-Management
      scriptName: SearchAlertsV2
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#error#':
      - "4"
      '#none#':
      - "6"
    scriptarguments:
      fromdate:
        simple: 1 hour ago
      limit:
        simple: "500"
    separatecontext: false
    continueonerror: true
    continueonerrortype: errorPath
    view: |-
      {
        "position": {
          "x": 195.25,
          "y": 210
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 2338a1f5-43e7-41a8-89ce-52b874c47e2f
    type: regular
    task:
      id: 2338a1f5-43e7-41a8-89ce-52b874c47e2f
      version: -1
      name: Close Investigation
      description: commands.local.cmd.close.inv
      script: Builtin|||closeInvestigation
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#error#':
      - "4"
      '#none#':
      - "5"
    separatecontext: false
    continueonerror: true
    continueonerrortype: errorPath
    view: |-
      {
        "position": {
          "x": 340.5,
          "y": 550
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 1d0c04dc-71bc-4667-8b3e-49b4339eb081
    type: playbook
    task:
      id: 1d0c04dc-71bc-4667-8b3e-49b4339eb081
      version: -1
      name: Foundation - Error Handling
      playbookName: Foundation - Error Handling
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    separatecontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 455bc6dc-2b02-4b09-8faf-9d84988ac0fe
    type: title
    task:
      id: 455bc6dc-2b02-4b09-8faf-9d84988ac0fe
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 195.25,
          "y": 890
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: 367553c1-9597-4413-88e5-39b5b6814fa3
    type: playbook
    task:
      id: 367553c1-9597-4413-88e5-39b5b6814fa3
      version: -1
      name: Get Alert Tasks and Store to Dataset
      playbookName: Get Alert Tasks and Store to Dataset
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      Alert:
        simple: ${foundIncidents}
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 340.5,
          "y": 380
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 900,
        "width": 671.5,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
quiet: true
dirtyInputs: true
