dirtyInputs: true
id: 0c636b23-4aaa-4eb4-84d8-e2d77cc5182b
inputSections:
- description: Generic group for inputs
  inputs:
  - Production
  name: General (Inputs group)
inputs:
- description: yes or no
  key: Production
  playbookInputQuery: null
  required: false
  value:
    simple: "yes"
name: Foundation - Upon Trigger
outputSections:
- description: Generic group for outputs
  name: General (Outputs group)
  outputs:
  - Shadow
outputs:
- contextPath: Shadow
  type: boolean
starttaskid: "0"
tags:
- SOC
- PoV
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 5206068f-fdf3-4829-8cc2-c3ada7b5516b
      iscommand: false
      name: ""
      version: -1
    taskid: 5206068f-fdf3-4829-8cc2-c3ada7b5516b
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "17"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: cd6cbd33-49b9-4c0e-8c76-12c43c541cb5
      iscommand: false
      name: Environment Detection
      type: title
      version: -1
    taskid: cd6cbd33-49b9-4c0e-8c76-12c43c541cb5
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: eaffbc30-3533-483b-80c1-82bdd0e73dd3
      iscommand: false
      name: Data Integrity
      type: title
      version: -1
    taskid: eaffbc30-3533-483b-80c1-82bdd0e73dd3
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 265,
          "y": 690
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 2b3a538a-4c64-408a-86b2-74cd81484c7f
      iscommand: false
      name: Incident Sync (Ledger / Owner Notification)
      type: title
      version: -1
    taskid: 2b3a538a-4c64-408a-86b2-74cd81484c7f
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 265,
          "y": 835
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "22"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4bc7c9d9-c8d2-4e49-8f24-1e964e9ad270
      iscommand: false
      name: Dedup
      type: title
      version: -1
    taskid: 4bc7c9d9-c8d2-4e49-8f24-1e964e9ad270
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 265,
          "y": 980
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: a4730ca6-80a0-4fb3-80d3-9a2e6e1f964c
      iscommand: false
      name: Enrichment (User, IP, Hash, Domain)
      type: title
      version: -1
    taskid: a4730ca6-80a0-4fb3-80d3-9a2e6e1f964c
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1300
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 35c54f0f-e1e7-48a9-8aed-57d322ddf9c7
      iscommand: false
      name: Assessment
      type: title
      version: -1
    taskid: 35c54f0f-e1e7-48a9-8aed-57d322ddf9c7
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1445
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "23"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 76dd4bf8-4839-4846-8cc2-95492ce2721a
      iscommand: false
      name: Escalation
      type: title
      version: -1
    taskid: 76dd4bf8-4839-4846-8cc2-95492ce2721a
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1590
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d6a23a94-520a-4ff6-8146-c309f064e6ed
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: d6a23a94-520a-4ff6-8146-c309f064e6ed
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1910
        }
      }
  "17":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${inputs.Production}
          operator: isEqualString
          right:
            value:
              simple: "yes"
      label: "yes"
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${inputs.Production}
          operator: isEqualString
          right:
            value:
              simple: "no"
      label: "no"
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "18"
      "yes":
      - "19"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b97e8221-5b48-4730-8b31-ac942ab7adf6
      iscommand: false
      name: Is this a Production Environment?
      type: condition
      version: -1
    taskid: b97e8221-5b48-4730-8b31-ac942ab7adf6
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 265,
          "y": 340
        }
      }
  "18":
    continueonerrortype: ""
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: shadow_mode
      value:
        simple: "true"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: 66c49472-c91c-487c-8fc7-82ecb59998c6
      iscommand: false
      name: Set To Shadow
      script: Set
      type: regular
      version: -1
    taskid: 66c49472-c91c-487c-8fc7-82ecb59998c6
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 515
        }
      }
  "19":
    continueonerrortype: ""
    id: "19"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: shadow_mode
      value:
        simple: "false"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: 56ad1656-4445-4231-8a93-347adc7a1a90
      iscommand: false
      name: Set To Full Run
      script: Set
      type: regular
      version: -1
    taskid: 56ad1656-4445-4231-8a93-347adc7a1a90
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 515
        }
      }
  "22":
    continueonerrortype: ""
    id: "22"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: A simple Dedup to insure alerts are not executed on more than once.
      id: affbdad4-0d9f-4822-8ff0-30bdda250e0e
      iscommand: false
      name: Foundation - Dedup
      playbookId: 7afa7e4b-9f55-4627-8381-ebd0c92b69ad
      type: playbook
      version: -1
    taskid: affbdad4-0d9f-4822-8ff0-30bdda250e0e
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1125
        }
      }
  "23":
    continueonerrortype: ""
    id: "23"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 7997dc98-7fbe-4eb1-8045-5bfa1978784a
      iscommand: false
      name: Foundation - Enrichment
      playbookId: 84c5e8a5-998c-4d01-801e-7d03ef3394d3
      type: playbook
      version: -1
    taskid: 7997dc98-7fbe-4eb1-8045-5bfa1978784a
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1735
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1925,
        "width": 810,
        "x": 50,
        "y": 50
      }
    }
  }
