dirtyInputs: true
id: 'JOB - Triage Incidents'
inputs: []
name: JOB - Triage Incidents
outputs: []
quiet: true
starttaskid: "0"
tags:
- SOC_Framework
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e017f7b2-15dc-4408-8530-1bedbbbe5c72
      iscommand: false
      name: ""
      version: -1
    taskid: e017f7b2-15dc-4408-8530-1bedbbbe5c72
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 240.5,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: errorPath
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "6"
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      body:
        simple: '{"request_data" : {"filters" : [{"field": "status","operator": "eq","value":
          "New"},{"operator": "lte", "value": ${TimeNowUnix}, "field": "modification_time"},{"operator":
          "eq", "value": "false", "field": "starred"}]}}'
      extend-context:
        simple: Found=.
      uri:
        simple: /public_api/v1/incidents/get_incidents
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: send HTTP POST request.
      id: 9ae0e2cd-eac0-4ee2-8abf-81e8415f05af
      iscommand: true
      name: Get Incidents
      script: '|||core-api-post'
      type: regular
      version: -1
    taskid: 9ae0e2cd-eac0-4ee2-8abf-81e8415f05af
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 385.75,
          "y": 380
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      forEach: true
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      Incident:
        simple: ${Found.response.reply.incidents}
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 94b05767-4822-4ae1-8f66-53b98234d58a
      iscommand: false
      name: Close Incidents
      playbookId: 'Close Incidents'
      type: playbook
      version: -1
    taskid: 94b05767-4822-4ae1-8f66-53b98234d58a
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 385.75,
          "y": 720
        }
      }
  "3":
    continueonerror: true
    continueonerrortype: errorPath
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "6"
      '#none#':
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      hoursAgo:
        simple: "6"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Retrieves the current date and time.
      id: 0b8f86fd-faba-4add-ba9f-474a2df363b3
      iscommand: false
      name: Get Time
      script: GetTime
      type: regular
      version: -1
    taskid: 0b8f86fd-faba-4add-ba9f-474a2df363b3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 240.5,
          "y": 210
        }
      }
  "4":
    continueonerror: true
    continueonerrortype: errorPath
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "6"
      '#none#':
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: 21d546a1-f8fd-4993-a575-6bcb30005435
      iscommand: true
      name: Close
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: 21d546a1-f8fd-4993-a575-6bcb30005435
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 531,
          "y": 890
        }
      }
  "5":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Found.response.reply.incidents.incident_id
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 2a934d58-f94b-41b6-85b0-cf069a19ec88
      iscommand: false
      name: Incidents to Triage?
      type: condition
      version: -1
    taskid: 2a934d58-f94b-41b6-85b0-cf069a19ec88
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 531,
          "y": 550
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: f9f44a29-0a52-4a67-88d2-715faefa19fa
      iscommand: false
      name: Foundation - Error Handling
      playbookId: 'Foundation - Error Handling'
      type: playbook
      version: -1
    taskid: f9f44a29-0a52-4a67-88d2-715faefa19fa
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1060
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: bf546b3b-1d71-48ed-9a20-bff3bad3242a
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: bf546b3b-1d71-48ed-9a20-bff3bad3242a
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 581,
          "y": 1065
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1080,
        "width": 912,
        "x": 50,
        "y": 50
      }
    }
  }
