id: 7afa7e4b-9f55-4627-8381-ebd0c92b69ad
version: 10
vcShouldKeepItemLegacyProdMachine: false
name: Foundation - Dedup
description: A simple Dedup to insure alerts are not executed on more than once.
tags:
- SOC
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 4bb50423-9a1a-4c0e-88ba-c31e26fdf280
    type: start
    task:
      id: 4bb50423-9a1a-4c0e-88ba-c31e26fdf280
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: 2eb08148-d069-489a-83e1-1ab88016aac3
    type: title
    task:
      id: 2eb08148-d069-489a-83e1-1ab88016aac3
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 930
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: fdf50b61-67fa-450a-8450-0b0d9966a403
    type: regular
    task:
      id: fdf50b61-67fa-450a-8450-0b0d9966a403
      version: -1
      name: DeDup Alerts from the Last "1 days ago"
      description: Find past similar alerts based on alert fields' similarity. Includes
        an option to also display indicators similarity.
      scriptName: DBotFindSimilarAlerts
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "16"
    scriptarguments:
      fromDate:
        simple: 1 days ago
      minimunIncidentSimilarity:
        simple: "0.8"
      query:
        simple: case_id=${parentIncidentFields.incident_id}
      similarJsonField:
        simple: username,hostip
      similarTextField:
        simple: name,type
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "14":
    id: "14"
    taskid: 1aabd3a7-6f8a-4253-8719-f48488f63d62
    type: regular
    task:
      id: 1aabd3a7-6f8a-4253-8719-f48488f63d62
      version: -1
      name: Close As Duplicates
      description: commands.local.cmd.close.inv
      script: Builtin|||closeInvestigation
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      closeNotes:
        simple: Auto-Close Duplicate
      closeReason:
        simple: Resolved - Duplicate Alert
      id:
        simple: ${DBotFindSimilarIncidents.similarIncident.id}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 2
    isoversize: false
    isautoswitchedtoquietmode: false
  "15":
    id: "15"
    taskid: f8eea1f8-0d66-477e-87f1-a1beac4651d1
    type: regular
    task:
      id: f8eea1f8-0d66-477e-87f1-a1beac4651d1
      version: -1
      name: Print Duplicate Alerts
      description: Prints text to war room (Markdown supported)
      scriptName: Print
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      value:
        simple: ${DBotFindSimilarIncidents.similarIncident.id}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "16":
    id: "16"
    taskid: 7adad498-fc30-4def-818b-a1d7198474c8
    type: condition
    task:
      id: 7adad498-fc30-4def-818b-a1d7198474c8
      version: -1
      name: Are there any similar alerts?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "8"
      "yes":
      - "15"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isTrue
          left:
            value:
              simple: DBotFindSimilarIncidents.isSimilarIncidentFound
            iscontext: true
          right:
            value: {}
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 945,
        "width": 492.5,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
sourceplaybookid: 0c636b23-4aaa-4eb4-84d8-e2d77cc5182b
quiet: true
dirtyInputs: true
