id: 19afce31-d945-4a44-800d-efd460f0c9f1
inputs: []
name: Use Case - Close NGFW Prevented
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 5481d500-924e-4af3-8d69-bf6a98b670f6
      iscommand: false
      name: ""
      version: -1
    taskid: 5481d500-924e-4af3-8d69-bf6a98b670f6
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: f37d1e85-3487-4838-8568-4910aaf76d0e
      iscommand: true
      name: Close Alert
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: f37d1e85-3487-4838-8568-4910aaf76d0e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      type:
        simple: NGFW Prevented
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: e460eb0d-de17-42fa-8960-d9d230588fbc
      iscommand: true
      name: Set Alert Type
      script: Builtin|||setAlert
      type: regular
      version: -1
    taskid: e460eb0d-de17-42fa-8960-d9d230588fbc
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 6cbbb1c7-46a4-4e29-8a25-4b50459d35d3
      iscommand: false
      name: Foundation - Upon Trigger
      playbookId: 0c636b23-4aaa-4eb4-84d8-e2d77cc5182b
      type: playbook
      version: -1
    taskid: 6cbbb1c7-46a4-4e29-8a25-4b50459d35d3
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 590,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
