id: 9baee4e3-5735-4b58-8407-5c5ce6fbad91
version: 2
vcShouldKeepItemLegacyProdMachine: false
name: JOB - Triage Incidents
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 0875f54c-791e-49ee-880f-be235bb78f3d
    type: start
    task:
      id: 0875f54c-791e-49ee-880f-be235bb78f3d
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 195.25,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: aa1373e0-bd9c-47b3-8e3c-100e987e7ae0
    type: regular
    task:
      id: aa1373e0-bd9c-47b3-8e3c-100e987e7ae0
      version: -1
      name: Get Incidents
      description: send HTTP POST request.
      script: '|||core-api-post'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#error#':
      - "7"
      '#none#':
      - "5"
    scriptarguments:
      body:
        simple: '{"request_data" : {"filters" : [{"field": "status","operator": "eq","value":
          "New"},{"operator": "lte", "value": ${TimeNowUnix}, "field": "modification_time"},{"operator":
          "eq", "value": "false", "field": "starred"}]}}'
      extend-context:
        simple: Found=.
      uri:
        simple: /public_api/v1/incidents/get_incidents
    separatecontext: false
    continueonerror: true
    continueonerrortype: errorPath
    view: |-
      {
        "position": {
          "x": 340.5,
          "y": 380
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: ccfb4428-0980-40d9-8df8-c150d017b41e
    type: playbook
    task:
      id: ccfb4428-0980-40d9-8df8-c150d017b41e
      version: -1
      name: Close Incidents
      playbookName: Close Incidents
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      Incident:
        simple: ${Found.response.reply.incidents}
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
      forEach: true
    view: |-
      {
        "position": {
          "x": 631,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 87a13724-fbd9-4444-9f16-374ca7b1a1af
    type: regular
    task:
      id: 87a13724-fbd9-4444-9f16-374ca7b1a1af
      version: -1
      name: Get Time
      description: |
        Retrieves the current date and time.
      scriptName: GetTime
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#error#':
      - "7"
      '#none#':
      - "1"
    scriptarguments:
      hoursAgo:
        simple: "6"
    separatecontext: false
    continueonerror: true
    continueonerrortype: errorPath
    view: |-
      {
        "position": {
          "x": 195.25,
          "y": 210
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 871774cd-53c6-46ff-b5d9-e83219402a97
    type: regular
    task:
      id: 871774cd-53c6-46ff-b5d9-e83219402a97
      version: -1
      name: Close
      description: commands.local.cmd.close.inv
      script: Builtin|||closeInvestigation
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#error#':
      - "7"
      '#none#':
      - "6"
    separatecontext: false
    continueonerror: true
    continueonerrortype: errorPath
    view: |-
      {
        "position": {
          "x": 485.75,
          "y": 890
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 1c414651-edf9-48bb-85df-0913e1cb6d54
    type: condition
    task:
      id: 1c414651-edf9-48bb-85df-0913e1cb6d54
      version: -1
      name: Incidents to Triage?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "2"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: Found.response.reply.incidents.incident_id
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 485.75,
          "y": 550
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: 36a3a807-f1bf-41cc-8175-65b1fab10552
    type: title
    task:
      id: 36a3a807-f1bf-41cc-8175-65b1fab10552
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 290.5,
          "y": 1230
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: 58fa4e3d-dd84-41ce-8f67-ea6e1aefe29a
    type: playbook
    task:
      id: 58fa4e3d-dd84-41ce-8f67-ea6e1aefe29a
      version: -1
      name: Foundation - Error Handling
      playbookName: Foundation - Error Handling
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    separatecontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1060
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1240,
        "width": 962,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
quiet: true
dirtyInputs: true
