dirtyInputs: true
id: 84c5e8a5-998c-4d01-801e-7d03ef3394d3
inputs: []
name: Foundation - Enrichment
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
      - "9"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8492b25a-a19c-4593-8191-9cb60e4d3007
      iscommand: false
      name: ""
      version: -1
    taskid: 8492b25a-a19c-4593-8191-9cb60e4d3007
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
  "2":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: alert.sourceip
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "5"
      "yes":
      - "10"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ba15e72f-a381-4b97-8e51-7937092bfaf6
      iscommand: false
      name: Is Source IP Defined?
      type: condition
      version: -1
    taskid: ba15e72f-a381-4b97-8e51-7937092bfaf6
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 480,
          "y": 340
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 6b3dbf1c-9a22-4bd4-8593-bc8d49dcc7c0
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 6b3dbf1c-9a22-4bd4-8593-bc8d49dcc7c0
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1040
        }
      }
  "5":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: alert.destinationip
          operator: isExists
          right:
            value: {}
      label: "yes"
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "11"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 2eae8f2e-1cc9-4120-88e0-1e70e0be6069
      iscommand: false
      name: Is Destination IP Defined?
      type: condition
      version: -1
    taskid: 2eae8f2e-1cc9-4120-88e0-1e70e0be6069
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 480,
          "y": 690
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 921bdd5d-2fab-4996-8682-a5e6f80b9aca
      iscommand: false
      name: Email Enrichment
      type: title
      version: -1
    taskid: 921bdd5d-2fab-4996-8682-a5e6f80b9aca
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 02dc9df5-d1cf-4475-83a6-dc33e09fc4fe
      iscommand: false
      name: IP Enrichment
      type: title
      version: -1
    taskid: 02dc9df5-d1cf-4475-83a6-dc33e09fc4fe
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
  "10":
    continueonerror: true
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      ip:
        simple: ${alert.sourceip}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Provides data enrichment for ips.
      id: f33cce94-afea-4e36-8fc2-74eeed0db1a4
      iscommand: true
      name: Enrich Source IP
      script: '|||ip'
      type: regular
      version: -1
    taskid: f33cce94-afea-4e36-8fc2-74eeed0db1a4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 592.5,
          "y": 515
        }
      }
  "11":
    continueonerror: true
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      ip:
        simple: ${alert.destinationip}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Provides data enrichment for ips.
      id: 2821bcfc-c76c-4551-80c7-08061164a907
      iscommand: true
      name: Enrich Destination IP
      script: '|||ip'
      type: regular
      version: -1
    taskid: 2821bcfc-c76c-4551-80c7-08061164a907
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 592.5,
          "y": 865
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1055,
        "width": 922.5,
        "x": 50,
        "y": 50
      }
    }
  }
