dirtyInputs: true
id: JOB - Triage Incidents
inputs: []
name: JOB - Triage Incidents
outputs: []
quiet: true
starttaskid: "0"
tags:
- SOC_Framework
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9b745ac1-d45c-4d0c-8846-7b3dcb65d3ad
      iscommand: false
      name: ""
      version: -1
    taskid: 9b745ac1-d45c-4d0c-8846-7b3dcb65d3ad
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 290.5,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: errorPath
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "6"
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      body:
        simple: '{"request_data" : {"filters" : [{"field": "status","operator": "eq","value":
          "New"},{"operator": "lte", "value": ${TimeNowUnix}, "field": "modification_time"},{"operator":
          "eq", "value": "false", "field": "starred"}]}}'
      extend-context:
        simple: Found=.
      uri:
        simple: /public_api/v1/incidents/get_incidents
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: send HTTP POST request.
      id: 6e2b45a2-1134-4746-8fa0-9010532432d8
      iscommand: true
      name: Get Incidents
      script: '|||core-api-post'
      type: regular
      version: -1
    taskid: 6e2b45a2-1134-4746-8fa0-9010532432d8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 481,
          "y": 380
        }
      }
  "3":
    continueonerror: true
    continueonerrortype: errorPath
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "6"
      '#none#':
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      hoursAgo:
        simple: "6"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Retrieves the current date and time.
      id: 6bedbe98-6973-43e3-888a-b19c039e6574
      iscommand: false
      name: Get Time
      script: GetTime
      type: regular
      version: -1
    taskid: 6bedbe98-6973-43e3-888a-b19c039e6574
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 290.5,
          "y": 210
        }
      }
  "5":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Found.response.reply.incidents.incident_id
          operator: isExists
          right:
            value: {}
      label: "yes"
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "7"
      "yes":
      - "8"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 5776a330-7878-436f-8cc8-17e603b4f0f2
      iscommand: false
      name: Incidents to Triage?
      type: condition
      version: -1
    taskid: 5776a330-7878-436f-8cc8-17e603b4f0f2
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 531,
          "y": 550
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 5f959f5a-c36c-4409-8646-003db68f88d6
      iscommand: false
      name: Foundation - Error Handling
      playbookId: Foundation - Error Handling
      type: playbook
      version: -1
    taskid: 5f959f5a-c36c-4409-8646-003db68f88d6
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 550
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 770694c8-81b1-4843-8cb1-0f0bd6134dd9
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 770694c8-81b1-4843-8cb1-0f0bd6134dd9
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 340.5,
          "y": 890
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      forEach: true
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      incident_id:
        simple: ${Found.response.reply.incidents.incident_id}
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 099ae5a2-fa98-4412-80b3-747732160606
      iscommand: false
      name: Close Incidents
      playbookId: 97f87182-252c-454b-810d-c951e39abe9d
      type: playbook
      version: -1
    taskid: 099ae5a2-fa98-4412-80b3-747732160606
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 676.25,
          "y": 720
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 900,
        "width": 1007.25,
        "x": 50,
        "y": 50
      }
    }
  }
