id: JOB - Triage Incidents
version: 3
vcShouldKeepItemLegacyProdMachine: false
name: JOB - Triage Incidents
tags:
- SOC_Framework
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: e017f7b2-15dc-4408-8530-1bedbbbe5c72
    type: start
    task:
      id: e017f7b2-15dc-4408-8530-1bedbbbe5c72
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 240.5,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 9ae0e2cd-eac0-4ee2-8abf-81e8415f05af
    type: regular
    task:
      id: 9ae0e2cd-eac0-4ee2-8abf-81e8415f05af
      version: -1
      name: Get Incidents
      description: send HTTP POST request.
      script: '|||core-api-post'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#error#':
      - "6"
      '#none#':
      - "5"
    scriptarguments:
      body:
        simple: '{"request_data" : {"filters" : [{"field": "status","operator": "eq","value":
          "New"},{"operator": "lte", "value": ${TimeNowUnix}, "field": "modification_time"},{"operator":
          "eq", "value": "false", "field": "starred"}]}}'
      extend-context:
        simple: Found=.
      uri:
        simple: /public_api/v1/incidents/get_incidents
    separatecontext: false
    continueonerror: true
    continueonerrortype: errorPath
    view: |-
      {
        "position": {
          "x": 385.75,
          "y": 380
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 0b8f86fd-faba-4add-ba9f-474a2df363b3
    type: regular
    task:
      id: 0b8f86fd-faba-4add-ba9f-474a2df363b3
      version: -1
      name: Get Time
      description: |
        Retrieves the current date and time.
      scriptName: GetTime
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#error#':
      - "6"
      '#none#':
      - "1"
    scriptarguments:
      hoursAgo:
        simple: "6"
    separatecontext: false
    continueonerror: true
    continueonerrortype: errorPath
    view: |-
      {
        "position": {
          "x": 240.5,
          "y": 210
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 21d546a1-f8fd-4993-a575-6bcb30005435
    type: regular
    task:
      id: 21d546a1-f8fd-4993-a575-6bcb30005435
      version: -1
      name: Close
      description: commands.local.cmd.close.inv
      script: Builtin|||closeInvestigation
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#error#':
      - "6"
      '#none#':
      - "7"
    separatecontext: false
    continueonerror: true
    continueonerrortype: errorPath
    view: |-
      {
        "position": {
          "x": 531,
          "y": 890
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 2a934d58-f94b-41b6-85b0-cf069a19ec88
    type: condition
    task:
      id: 2a934d58-f94b-41b6-85b0-cf069a19ec88
      version: -1
      name: Incidents to Triage?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "8"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: Found.response.reply.incidents.incident_id
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 531,
          "y": 550
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: f9f44a29-0a52-4a67-88d2-715faefa19fa
    type: playbook
    task:
      id: f9f44a29-0a52-4a67-88d2-715faefa19fa
      version: -1
      name: Foundation - Error Handling
      playbookName: Foundation - Error Handling
      type: playbook
      iscommand: false
      brand: ""
    separatecontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1060
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: bf546b3b-1d71-48ed-9a20-bff3bad3242a
    type: title
    task:
      id: bf546b3b-1d71-48ed-9a20-bff3bad3242a
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 581,
          "y": 1065
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: 53391bc1-20c5-4d23-85c5-80a903904c17
    type: playbook
    task:
      id: 53391bc1-20c5-4d23-85c5-80a903904c17
      version: -1
      name: Close Incidents
      playbookName: Close Incidents
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    separatecontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 676.25,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {
      "5_8_yes": 0.83
    },
    "paper": {
      "dimensions": {
        "height": 1080,
        "width": 1007.25,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
quiet: true
dirtyInputs: true
