dirtyInputs: true
id: JOB - Triage Incidents
inputs: []
name: JOB - Triage Incidents
outputs: []
quiet: true
starttaskid: "0"
tags:
- SOC_Framework
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ef0db9e6-cb66-4744-8ec1-d010d2a2bb25
      iscommand: false
      name: ""
      version: -1
    taskid: ef0db9e6-cb66-4744-8ec1-d010d2a2bb25
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 240.5,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    continueonerrortype: errorPath
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "6"
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      body:
        simple: '{"request_data" : {"filters" : [{"field": "status","operator": "eq","value":
          "New"},{"operator": "lte", "value": ${TimeNowUnix}, "field": "modification_time"},{"operator":
          "eq", "value": "false", "field": "starred"}]}}'
      extend-context:
        simple: Found=.
      uri:
        simple: /public_api/v1/incidents/get_incidents
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: send HTTP POST request.
      id: 03980a65-9f73-4beb-8970-5774b57b5ecd
      iscommand: true
      name: Get Incidents
      script: '|||core-api-post'
      type: regular
      version: -1
    taskid: 03980a65-9f73-4beb-8970-5774b57b5ecd
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 385.75,
          "y": 380
        }
      }
  "3":
    continueonerror: true
    continueonerrortype: errorPath
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "6"
      '#none#':
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      hoursAgo:
        simple: "6"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Retrieves the current date and time.
      id: 3337799d-2919-4ba5-8a14-af608dc8dd51
      iscommand: false
      name: Get Time
      script: GetTime
      type: regular
      version: -1
    taskid: 3337799d-2919-4ba5-8a14-af608dc8dd51
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 240.5,
          "y": 210
        }
      }
  "4":
    continueonerror: true
    continueonerrortype: errorPath
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "6"
      '#none#':
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: e65ec0f8-cefc-46cc-8ebe-dc8e52aee135
      iscommand: true
      name: Close
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: e65ec0f8-cefc-46cc-8ebe-dc8e52aee135
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 531,
          "y": 890
        }
      }
  "5":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Found.response.reply.incidents.incident_id
          operator: isExists
      label: "yes"
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "8"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: efd62489-c0be-4b3f-8634-90b1400026d1
      iscommand: false
      name: Incidents to Triage?
      type: condition
      version: -1
    taskid: efd62489-c0be-4b3f-8634-90b1400026d1
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 531,
          "y": 550
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 6022cef1-efad-4af2-8e12-42885fb4ae9b
      iscommand: false
      name: Foundation - Error Handling
      playbookId: Foundation - Error Handling
      type: playbook
      version: -1
    taskid: 6022cef1-efad-4af2-8e12-42885fb4ae9b
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1060
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: bd5e247a-beca-412e-8766-a3bdc0a9ff8d
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: bd5e247a-beca-412e-8766-a3bdc0a9ff8d
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 581,
          "y": 1065
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 0bc82109-f457-4230-8d72-40a476dcb3ef
      iscommand: false
      name: Close Incidents
      playbookId: 97f87182-252c-454b-810d-c951e39abe9d
      type: playbook
      version: -1
    taskid: 0bc82109-f457-4230-8d72-40a476dcb3ef
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 676.25,
          "y": 720
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "5_8_yes": 0.83
    },
    "paper": {
      "dimensions": {
        "height": 1080,
        "width": 1007.25,
        "x": 50,
        "y": 50
      }
    }
  }
