id: 97f87182-252c-454b-810d-c951e39abe9d
version: 8
vcShouldKeepItemLegacyProdMachine: false
name: Close Incidents
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 388b6c79-26c8-4e79-8102-5ca9735eec59
    type: start
    task:
      id: 388b6c79-26c8-4e79-8102-5ca9735eec59
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 195.25,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: b877ed7d-27c9-43b4-8f10-be5e08c162cc
    type: regular
    task:
      id: b877ed7d-27c9-43b4-8f10-be5e08c162cc
      version: -1
      name: Close Incident
      description: send HTTP POST request.
      script: '|||core-api-post'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      body:
        simple: '{"request_data":{"incident_id":"${inputs.Incident.incident_id}","update_data":{"status":"resolved_other","resolve_comment":"This
          incident is resolved"}}}'
      uri:
        simple: /public_api/v1/incidents/update_incident
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1060
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: c7bf93cb-abc8-4d9b-9ae1-b66dda8941f9
    type: regular
    task:
      id: c7bf93cb-abc8-4d9b-9ae1-b66dda8941f9
      version: -1
      name: Get Alerts on Incident
      description: send HTTP POST request.
      script: '|||core-api-post'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      body:
        simple: '{"request_data":{"incident_id":"${inputs.Incident.incident_id}",
          "alerts_limit":90}}'
      extend-context:
        simple: Alerts.response.reply.alerts.data.alert_id=response.reply.alerts.data.alert_id
      ignore-outputs:
        simple: "true"
      uri:
        simple: /public_api/v1/incidents/get_incident_extra_data
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 195.25,
          "y": 210
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 2
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 4ddaf994-3e26-4d9e-88ee-9f7230a44416
    type: condition
    task:
      id: 4ddaf994-3e26-4d9e-88ee-9f7230a44416
      version: -1
      name: Alerts Exist?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "7"
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: Alerts
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 195.25,
          "y": 380
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 9d40919b-c301-470d-a452-ace75db76c75
    type: regular
    task:
      id: 9d40919b-c301-470d-a452-ace75db76c75
      version: -1
      name: Batch Close Alerts
      description: send HTTP POST request.
      script: '|||core-api-post'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      body:
        simple: '{"request_data":{"alert_id_list":${Alerts.response.reply.alerts.data.alert_id},"update_data":{"status":"resolved_other","comment":"This
          alert is auto triaged"}}}'
      uri:
        simple: /public_api/v1/alerts/update_alerts
    separatecontext: false
    continueonerror: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 340.5,
          "y": 549
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 2
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 562c1c24-32f9-4615-8f50-ecab33206937
    type: regular
    task:
      id: 562c1c24-32f9-4615-8f50-ecab33206937
      version: -1
      name: Delete Context
      description: |-
        Delete field from context.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.10/Cortex-XSOAR-Administrator-Guide/Automations
      script: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      key:
        simple: Alerts
      subplaybook:
        simple: "yes"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 340.5,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: 2f478251-4ce8-413b-8712-a5dcd0d2a83e
    type: title
    task:
      id: 2f478251-4ce8-413b-8712-a5dcd0d2a83e
      version: -1
      name: Fin
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 195.25,
          "y": 1230
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: 1646142f-ee76-4a97-8e28-2feb971d46c8
    type: condition
    task:
      id: 1646142f-ee76-4a97-8e28-2feb971d46c8
      version: -1
      name: ASM Incident?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "6"
      "yes":
      - "1"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: containsGeneral
          left:
            value:
              simple: ${inputs.Incident.description}
            iscontext: true
          right:
            value:
              simple: ASM
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 195.25,
          "y": 890
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1240,
        "width": 671.5,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: Incident
  value: {}
  required: false
  description: ""
  playbookInputQuery: null
inputSections:
- inputs:
  - Incident
  name: General (Inputs group)
  description: Generic group for inputs
outputSections:
- outputs: []
  name: General (Outputs group)
  description: Generic group for outputs
outputs: []
dirtyInputs: true
