id: 45715d5b-7629-480c-85b2-5bed72884c70
version: 16
vcShouldKeepItemLegacyProdMachine: false
name: EntryPoint - Proofpoint TAP
tags:
- SOC
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 78b9e752-2392-4822-8a46-f9943ff20ce3
    type: start
    task:
      id: 78b9e752-2392-4822-8a46-f9943ff20ce3
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 5be56261-e91c-477a-8822-cd1b42c7465d
    type: playbook
    task:
      id: 5be56261-e91c-477a-8822-cd1b42c7465d
      version: -1
      name: Foundation - Upon Trigger
      playbookName: Foundation - Upon Trigger
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 5a944f5c-db0b-43e6-8872-a7cfe30e1fef
    type: title
    task:
      id: 5a944f5c-db0b-43e6-8872-a7cfe30e1fef
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 6d78e6eb-9031-4893-8f22-b578dde09cb7
    type: condition
    task:
      id: 6d78e6eb-9031-4893-8f22-b578dde09cb7
      version: -1
      name: Which Use Case is This?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      Click Permitted:
      - "8"
      Malicious Message Delivered:
      - "6"
    separatecontext: false
    conditions:
    - label: Malicious Message Delivered
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: alert.name
            iscontext: true
          right:
            value:
              simple: THD-Proofpoint_TAP-Malicious Message Delivered
    - label: Click Permitted
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: alert.name
            iscontext: true
          right:
            value:
              simple: THD-Proofpoint_TAP-Click Permitted
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: d24f99b2-98d5-4c6f-8950-ec5ee70799dc
    type: playbook
    task:
      id: d24f99b2-98d5-4c6f-8950-ec5ee70799dc
      version: -1
      name: Use Case - Phishing Malicious Message Delivered
      playbookName: Use Case - Phishing Malicious Message Delivered
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    separatecontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: 127882c5-2eac-4c2d-8a78-9aea79632367
    type: playbook
    task:
      id: 127882c5-2eac-4c2d-8a78-9aea79632367
      version: -1
      name: Use Case - Phishing Click Permitted
      playbookName: Use Case - Phishing Click Permitted
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    separatecontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 500,
          "y": 520
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {
      "4_6_Malicious Message Delivered": 0.88,
      "4_8_Click Permitted": 0.79
    },
    "paper": {
      "dimensions": {
        "height": 735,
        "width": 830,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
quiet: true
