id: f6904575-f749-4084-8ef3-5badb284fa42
version: 29
vcShouldKeepItemLegacyProdMachine: false
name: EntryPoint - XDR Agent
tags:
- SOC
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: ecef06c2-30d4-467a-8ae6-a51394772c7e
    type: start
    task:
      id: ecef06c2-30d4-467a-8ae6-a51394772c7e
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 480,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 56118752-6286-41c4-89b7-9783e876eee2
    type: playbook
    task:
      id: 56118752-6286-41c4-89b7-9783e876eee2
      version: -1
      name: Foundation - Upon Trigger
      playbookName: Foundation - Upon Trigger
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 2bd513af-c9d4-439a-81a2-e64566bea25a
    type: condition
    task:
      id: 2bd513af-c9d4-439a-81a2-e64566bea25a
      version: -1
      name: Which Use Case Is This?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "5"
      use case - arp -a:
      - "10"
      use case - hostname:
      - "7"
      use case - ifconfig:
      - "9"
      use case - whoami:
      - "8"
    separatecontext: false
    conditions:
    - label: use case - hostname
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: alert.name
            iscontext: true
          right:
            value:
              simple: Hostname Execution - Atomic T1082
    - label: use case - whoami
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: alert.name
            iscontext: true
          right:
            value:
              simple: WhoamI Execution
    - label: use case - ifconfig
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: alert.name
            iscontext: true
          right:
            value:
              simple: IfConfig Execution
    - label: use case - arp -a
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: alert.name
            iscontext: true
          right:
            value:
              simple: Arp -a Execution
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 480,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: e4ca0723-7c2c-44d0-8111-69e70bae45f7
    type: title
    task:
      id: e4ca0723-7c2c-44d0-8111-69e70bae45f7
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 480,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: de1eab47-109e-439d-88d4-b628d54bf261
    type: playbook
    task:
      id: de1eab47-109e-439d-88d4-b628d54bf261
      version: -1
      name: Use Case - Hostname Execution
      description: 'The hostname has been executed on a host with XDR agent.  This
        mostly for testing.  '
      playbookName: Use Case - Hostname Execution
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      Shadow:
        simple: "false"
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: 8baff362-d852-4e40-8223-3f6d10dc5267
    type: playbook
    task:
      id: 8baff362-d852-4e40-8223-3f6d10dc5267
      version: -1
      name: Use Case - WhoamI Execution
      playbookName: Use Case - WhoamI Execution
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    separatecontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: c956d836-013c-449c-8f8a-1268534eff5f
    type: playbook
    task:
      id: c956d836-013c-449c-8f8a-1268534eff5f
      version: -1
      name: Use Case - Ifconfig Execution
      playbookName: Use Case - Ifconfig Execution
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    separatecontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 910,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: 05742745-1397-4c9d-8075-e97d00b59563
    type: playbook
    task:
      id: 05742745-1397-4c9d-8075-e97d00b59563
      version: -1
      name: Use Case - ARP -A Execution
      playbookName: Use Case - ARP -A Execution
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    separatecontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {
      "4_8_use case - whoami": 0.89
    },
    "paper": {
      "dimensions": {
        "height": 735,
        "width": 1670,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
quiet: true
