dirtyInputs: true
id: 'EP_DefenseEvasion'
inputSections:
- description: Generic group for inputs
  inputs:
  - EntryPoint
  name: General (Inputs group)
inputs:
- description: ""
  key: EntryPoint
  playbookInputQuery: null
  required: false
  value:
    simple: EP_DefenseEvasion
name: EP_DefenseEvasion
outputSections:
- description: Generic group for outputs
  name: General (Outputs group)
  outputs: []
outputs: []
sourceplaybookid: 51ffcd5a-f5bb-4e09-84ae-e1efdc5165ac
starttaskid: "0"
tags:
- MITRE
- SOC
- SOC_Framework
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 09476d91-0723-46b6-89a2-d045e698d8c2
      iscommand: false
      name: ""
      version: -1
    taskid: 09476d91-0723-46b6-89a2-d045e698d8c2
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 275,
          "y": 50
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      EntryPoint:
        simple: ${inputs.EntryPoint}
      keyName:
        simple: PlaybookRoutes
      listName:
        simple: PlaybookDeploymentMatrix
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: edb5e094-b11c-4c3d-918f-73cdec0154cf
      iscommand: false
      name: Foundation - Playbook Router
      playbookId: 'Foundation - Playbook Router'
      type: playbook
      version: -1
    taskid: edb5e094-b11c-4c3d-918f-73cdec0154cf
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 275,
          "y": 550
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 5682800d-a684-4206-bca5-177dab874eeb
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 5682800d-a684-4206-bca5-177dab874eeb
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 275,
          "y": 1230
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 8c044a6d-ec6e-49dc-8eb6-451073549b2a
      iscommand: false
      name: Foundation - Upon Trigger
      playbookId: Foundation - Upon Trigger
      type: playbook
      version: -1
    taskid: 8c044a6d-ec6e-49dc-8eb6-451073549b2a
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 275,
          "y": 380
        }
      }
  "5":
    continueonerror: true
    continueonerrortype: errorPath
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#error#':
      - "7"
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      alertId:
        simple: ${alert.internal_id}
      name:
        simple: ${PlaybookRouting.Playbook.Name}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.playbook
      id: 137cda38-f359-4ec5-9c77-e48be9a86240
      iscommand: true
      name: Run Playbook
      script: Builtin|||setPlaybook
      type: regular
      version: -1
    taskid: 137cda38-f359-4ec5-9c77-e48be9a86240
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 890
        }
      }
  "6":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ${PlaybookRouting.Playbook.Name}
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4e430836-d68d-4c9c-a76f-49d05dd8174b
      iscommand: false
      name: Playbook Name Exists?
      type: condition
      version: -1
    taskid: 4e430836-d68d-4c9c-a76f-49d05dd8174b
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 275,
          "y": 720
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 847acd40-89de-417b-82eb-28bab05459f6
      iscommand: false
      name: Foundation - Error Handling
      playbookId: Foundation - Error Handling
      type: playbook
      version: -1
    taskid: 847acd40-89de-417b-82eb-28bab05459f6
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1060
        }
      }
  "8":
    continueonerrortype: ""
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: PlaybookRouting
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: "Delete field from context.\n\nThis automation runs using the default
        Limited User role, unless you explicitly change the permissions.\nFor more
        information, see the section about permissions here:\n- For Cortex XSOAR 6
        see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.x/Cortex-XSOAR-Playbook-Design-Guide/Automations
        \n- For Cortex XSOAR 8 Cloud see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8/Cortex-XSOAR-Cloud-Documentation/Create-a-script\n-
        For Cortex XSOAR 8.7 On-prem see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8.7/Cortex-XSOAR-On-prem-Documentation/Create-a-script"
      id: c30c65fc-ad22-4134-8f52-025b36bcb269
      iscommand: false
      name: Delete PlaybookRouting Context
      script: DeleteContext
      type: regular
      version: -1
    taskid: c30c65fc-ad22-4134-8f52-025b36bcb269
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 275,
          "y": 210
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1240,
        "width": 605,
        "x": 50,
        "y": 50
      }
    }
  }
