id: 477b10a5-11f5-430c-8884-282c63aae42a
version: 32
vcShouldKeepItemLegacyProdMachine: false
name: Foundation - Set SOC Metric Value Tag
description: This sends the current metric to the SOC Metrics dataset via an HTTP
  Collector.
tags:
- SOC
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: b81f6dfa-3912-491a-8a95-c5827f7ccb9c
    type: start
    task:
      id: b81f6dfa-3912-491a-8a95-c5827f7ccb9c
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 25535f04-5297-40ce-8cd0-8675fd1be74f
    type: regular
    task:
      id: 25535f04-5297-40ce-8cd0-8675fd1be74f
      version: -1
      name: Record Value Tag
      scriptName: RecordValueTag
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      Category:
        simple: ${inputs.Category}
      Tag:
        simple: ${inputs.Tag}
      Value:
        simple: ${inputs.Value}
      alertID:
        simple: ${inputs.alertID}
      alertName:
        simple: ${inputs.alertName}
      httpKey:
        simple: '{TOMMED}Vj/5yQCeYjqdYKtXoc0YO2wQ1IIZxLTuFGtGftJBVQBQ40LK8lAV3WAxFEkUz0M2s2ua0bW0P90DWY2+02AiThk/yYm9Hn+c615WVAq8EjMucrKedlk0pxMTNHxJEkUAVQ9MsYh+qXHnYbJA95AaMf6DQRnRSvLO8uovf2r035Adw8D4jFkJbxY0FqpeXyWViOTHYA6x55xcYfa2U9ukd/T5T7W/niBS1spsrBPzFKov5d5cJ+GQoVZ6vTElivFHWkYQrUuvZXeIYG5zxpxwUwPSLwK98iEPjFpDBkEtc/2Qba0dAo/Kj832pL8yuICY'
      httpURL:
        simple: https://api-brumxdr.xdr.us.paloaltonetworks.com/logs/v1/event
      listName:
        simple: ValueTags
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: f21608e8-38c9-468f-84be-04bf257ec0fe
    type: title
    task:
      id: f21608e8-38c9-468f-84be-04bf257ec0fe
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 385,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: Category
  value: {}
  required: true
  description: triage, enrichment, auto-remediation, assess, escalation
  playbookInputQuery: null
- key: Tag
  value: {}
  required: true
  description: Tag used when a specific automation i.e. enrichment_enrich_ip
  playbookInputQuery: null
- key: Value
  value: {}
  required: true
  description: Median time the task takes in minutes.
  playbookInputQuery: null
- key: alertID
  value:
    simple: ${alert.id}
  required: true
  description: The alert ID that fired this automation
  playbookInputQuery: null
- key: alertName
  value:
    simple: ${alert.name}
  required: true
  description: The alert name of the alert that fired this automation
  playbookInputQuery: null
inputSections:
- inputs:
  - Category
  - Tag
  - Value
  - alertID
  - alertName
  name: General (Inputs group)
  description: Generic group for inputs
outputSections:
- outputs: []
  name: General (Outputs group)
  description: Generic group for outputs
outputs: []
dirtyInputs: true
