id: 7afa7e4b-9f55-4627-8381-ebd0c92b69ad
version: 14
vcShouldKeepItemLegacyProdMachine: false
name: Foundation - Dedup
description: A simple Dedup to insure alerts are not executed on more than once.
tags:
- SOC
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 03c468b6-fc6c-42d4-8d5f-8e863c47d24d
    type: start
    task:
      id: 03c468b6-fc6c-42d4-8d5f-8e863c47d24d
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: d95bccea-d96f-4519-85db-79697b02c600
    type: title
    task:
      id: d95bccea-d96f-4519-85db-79697b02c600
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: 631f74bb-c7a5-4461-8fc7-54a830997d47
    type: regular
    task:
      id: 631f74bb-c7a5-4461-8fc7-54a830997d47
      version: -1
      name: DeDup Alerts from the Last "1 days ago"
      description: Find past similar alerts based on alert fields' similarity. Includes
        an option to also display indicators similarity.
      scriptName: DBotFindSimilarAlerts
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "16"
    scriptarguments:
      fromDate:
        simple: 1 days ago
      minimunIncidentSimilarity:
        simple: "0.8"
      query:
        simple: case_id=${parentIncidentFields.incident_id}
      similarJsonField:
        simple: username,hostip,mitreattcktactic
      similarTextField:
        simple: name,details
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "14":
    id: "14"
    taskid: bee11191-913c-4c42-80c9-55900a45567e
    type: regular
    task:
      id: bee11191-913c-4c42-80c9-55900a45567e
      version: -1
      name: Close As Duplicates
      description: commands.local.cmd.close.inv
      script: Builtin|||closeInvestigation
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      closeNotes:
        simple: Auto-Close Duplicate
      closeReason:
        simple: Resolved - Duplicate Alert
      id:
        simple: ${DBotFindSimilarIncidents.similarIncident.id}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 2
    isoversize: false
    isautoswitchedtoquietmode: false
  "15":
    id: "15"
    taskid: 5d8ed661-39b9-4c7c-8052-b90ba1821bf8
    type: regular
    task:
      id: 5d8ed661-39b9-4c7c-8052-b90ba1821bf8
      version: -1
      name: Print Duplicate Alerts
      description: Prints text to war room (Markdown supported)
      scriptName: Print
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      value:
        simple: ${DBotFindSimilarIncidents.similarIncident.id}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "16":
    id: "16"
    taskid: 340e5f95-12e7-41b2-8df4-41f18ecd750c
    type: condition
    task:
      id: 340e5f95-12e7-41b2-8df4-41f18ecd750c
      version: -1
      name: Are there any similar alerts?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "8"
      "yes":
      - "15"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isTrue
          left:
            value:
              simple: DBotFindSimilarIncidents.isSimilarIncidentFound
            iscontext: true
          right:
            value: {}
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 910,
        "width": 492.5,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
sourceplaybookid: 0c636b23-4aaa-4eb4-84d8-e2d77cc5182b
