id: 0c636b23-4aaa-4eb4-84d8-e2d77cc5182b
version: 86
vcShouldKeepItemLegacyProdMachine: false
name: Foundation - Upon Trigger
tags:
- SOC
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 03c468b6-fc6c-42d4-8d5f-8e863c47d24d
    type: start
    task:
      id: 03c468b6-fc6c-42d4-8d5f-8e863c47d24d
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 41c0c8bc-59d0-43db-8866-a153643e67cb
    type: title
    task:
      id: 41c0c8bc-59d0-43db-8866-a153643e67cb
      version: -1
      name: Environment Detection
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 24066021-473c-459d-8942-9108abed780a
    type: title
    task:
      id: 24066021-473c-459d-8942-9108abed780a
      version: -1
      name: Data Integrity
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 340
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 52dc2183-454c-4285-8f92-165827797b24
    type: title
    task:
      id: 52dc2183-454c-4285-8f92-165827797b24
      version: -1
      name: Incident Sync (Ledger / Owner Notification)
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 485
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: f077ae41-a242-41e0-8c92-87774be6a339
    type: title
    task:
      id: f077ae41-a242-41e0-8c92-87774be6a339
      version: -1
      name: Dedup
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "16"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 630
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 7aaf735b-5533-4809-8635-414fc31861ec
    type: title
    task:
      id: 7aaf735b-5533-4809-8635-414fc31861ec
      version: -1
      name: Enrichment (User, IP, Hash, Domain)
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 950
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: ab9e32c4-1492-4c64-8e9e-339775728946
    type: title
    task:
      id: ab9e32c4-1492-4c64-8e9e-339775728946
      version: -1
      name: Assessment
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1095
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: 121990cb-94e5-4afb-8e42-4f0fae4f947e
    type: title
    task:
      id: 121990cb-94e5-4afb-8e42-4f0fae4f947e
      version: -1
      name: Escalation
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1240
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: d95bccea-d96f-4519-85db-79697b02c600
    type: title
    task:
      id: d95bccea-d96f-4519-85db-79697b02c600
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1560
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: 9bd43b71-c8b0-4b0c-84a0-4882417cf6ec
    type: playbook
    task:
      id: 9bd43b71-c8b0-4b0c-84a0-4882417cf6ec
      version: -1
      name: Foundation - Set Triage Metric for SOC
      playbookName: Foundation - Set SOC Metric Value Tag
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      Category:
        simple: triage
      Tag:
        simple: triage_upon_trigger
      Value:
        simple: "5"
      alertID:
        simple: ${alert.id}
      alertName:
        simple: ${alert.name}
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1385
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "16":
    id: "16"
    taskid: bebe7b50-d189-461d-8eca-495973e52d0b
    type: playbook
    task:
      id: bebe7b50-d189-461d-8eca-495973e52d0b
      version: -1
      name: Foundation - Dedup
      playbookName: Foundation - Dedup
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    separatecontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 775
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1575,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
