id: Foundation - Upon Trigger
version: 1
contentitemexportablefields:
  contentitemfields:
    packID: soc-optimization
    packName: SOC Framework
    itemVersion: 2.1.10
    fromServerVersion: 5.0.0
    toServerVersion: ""
    definitionid: ""
    prevname: ""
    isoverridable: false
vcShouldKeepItemLegacyProdMachine: false
name: Foundation - Upon Trigger
tags:
  - SOC
  - SOC_Framework
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 5206068f-fdf3-4829-8cc2-c3ada7b5516b
    type: start
    task:
      id: 5206068f-fdf3-4829-8cc2-c3ada7b5516b
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
        - "1"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 275,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: cd6cbd33-49b9-4c0e-8c76-12c43c541cb5
    type: title
    task:
      id: cd6cbd33-49b9-4c0e-8c76-12c43c541cb5
      version: -1
      name: Environment Detection
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
        - "17"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 275,
          "y": 210
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: eaffbc30-3533-483b-80c1-82bdd0e73dd3
    type: title
    task:
      id: eaffbc30-3533-483b-80c1-82bdd0e73dd3
      version: -1
      name: Data Integrity
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
        - "3"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 715
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 2b3a538a-4c64-408a-86b2-74cd81484c7f
    type: title
    task:
      id: 2b3a538a-4c64-408a-86b2-74cd81484c7f
      version: -1
      name: Alert Sync (Ledger / Owner Notification)
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
        - "26"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 880
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 4bc7c9d9-c8d2-4e49-8f24-1e964e9ad270
    type: title
    task:
      id: 4bc7c9d9-c8d2-4e49-8f24-1e964e9ad270
      version: -1
      name: Dedup
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
        - "22"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1380
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: a4730ca6-80a0-4fb3-80d3-9a2e6e1f964c
    type: title
    task:
      id: a4730ca6-80a0-4fb3-80d3-9a2e6e1f964c
      version: -1
      name: Enrichment (User, IP, Hash, Domain)
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
        - "23"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1710
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: 35c54f0f-e1e7-48a9-8aed-57d322ddf9c7
    type: title
    task:
      id: 35c54f0f-e1e7-48a9-8aed-57d322ddf9c7
      version: -1
      name: Assessment
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
        - "7"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2040
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: 76dd4bf8-4839-4846-8cc2-95492ce2721a
    type: title
    task:
      id: 76dd4bf8-4839-4846-8cc2-95492ce2721a
      version: -1
      name: Escalation
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
        - "8"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2200
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: d6a23a94-520a-4ff6-8146-c309f064e6ed
    type: title
    task:
      id: d6a23a94-520a-4ff6-8146-c309f064e6ed
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 275,
          "y": 2360
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "17":
    id: "17"
    taskid: d1f1473c-003c-4c82-ac5a-07e0e82dad09
    type: condition
    task:
      id: d1f1473c-003c-4c82-ac5a-07e0e82dad09
      version: -1
      name: Is this a Production Environment?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
        - "18"
      "yes":
        - "19"
    scriptarguments:
      retry-count:
        simple: "0"
    separatecontext: false
    conditions:
      - label: "yes"
        condition:
          - - operator: isEqualString
              left:
                value:
                  simple: alert.env
                iscontext: true
              right:
                value:
                  simple: prod
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 275,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "18":
    id: "18"
    taskid: 67eedc50-5c07-4832-896d-f5b9780eb669
    type: regular
    task:
      id: 67eedc50-5c07-4832-896d-f5b9780eb669
      version: -1
      name: Set To Shadow
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#error#':
        - "24"
      '#none#':
        - "2"
    scriptarguments:
      key:
        simple: shadow_mode
      value:
        simple: "true"
    separatecontext: false
    continueonerror: true
    continueonerrortype: errorPath
    view: |-
      {
        "position": {
          "x": 60,
          "y": 540
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "19":
    id: "19"
    taskid: 5752dc90-12fe-48dd-99df-2df4c8d2a051
    type: regular
    task:
      id: 5752dc90-12fe-48dd-99df-2df4c8d2a051
      version: -1
      name: Set To Full Run
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#error#':
        - "24"
      '#none#':
        - "2"
    scriptarguments:
      key:
        simple: shadow_mode
      value:
        simple: "false"
    separatecontext: false
    continueonerror: true
    continueonerrortype: errorPath
    view: |-
      {
        "position": {
          "x": 490,
          "y": 540
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "22":
    id: "22"
    taskid: affbdad4-0d9f-4822-8ff0-30bdda250e0e
    type: playbook
    task:
      id: affbdad4-0d9f-4822-8ff0-30bdda250e0e
      version: -1
      name: Foundation - Dedup
      description: A simple Dedup to insure alerts are not executed on more than once.
      playbookName: Foundation - Dedup
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
        - "5"
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1540
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "23":
    id: "23"
    taskid: bf804660-d518-4cd7-87b5-4a5cbd2f4b47
    type: playbook
    task:
      id: bf804660-d518-4cd7-87b5-4a5cbd2f4b47
      version: -1
      name: Foundation - Enrichment
      playbookName: Foundation - Enrichment
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
        - "6"
    separatecontext: false
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1870
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "24":
    id: "24"
    taskid: bba69d32-a3b9-4a81-8d58-1be1e99e119f
    type: playbook
    task:
      id: bba69d32-a3b9-4a81-8d58-1be1e99e119f
      version: -1
      name: Foundation - Error Handling
      playbookName: Foundation - Error Handling
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
        - "8"
    separatecontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 500,
          "y": 710
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "25":
    id: "25"
    taskid: 164053c2-9f5b-487d-a444-b927f4266b8e
    type: regular
    task:
      id: 164053c2-9f5b-487d-a444-b927f4266b8e
      version: -1
      name: Normalize Entities in Context
      scriptName: SOC_NormalizeContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
        - "4"
    separatecontext: false
    continueonerror: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1210
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "26":
    id: "26"
    taskid: 4b283a1f-a5d4-42fa-8601-6f219d573515
    type: playbook
    task:
      id: 4b283a1f-a5d4-42fa-8601-6f219d573515
      version: -1
      name: Foundation Common - Extract Indicators from alerts
      playbookName: Foundation Common - Extract Indicators from alerts
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
        - "25"
    separatecontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1040
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
system: true
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2370,
        "width": 830,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
inputSections:
  - inputs: []
    name: General (Inputs group)
    description: Generic group for inputs
outputSections:
  - outputs:
      - Shadow
    name: General (Outputs group)
    description: Generic group for outputs
outputs:
  - contextPath: Shadow
    type: boolean
sourceplaybookid: Foundation - Upon Trigger
quiet: true
dirtyInputs: true
adopted: true
