id: dec57f34-ee9c-4c11-8f17-9812e700babe
version: 11
vcShouldKeepItemLegacyProdMachine: false
name: Shared Module - Ask User Email
tags:
- SOC
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 206016b7-4bee-48df-89e1-dfcc70124656
    type: start
    task:
      id: 206016b7-4bee-48df-89e1-dfcc70124656
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: d4124aee-965c-4585-83a6-a0fdd366217f
    type: playbook
    task:
      id: d4124aee-965c-4585-83a6-a0fdd366217f
      version: -1
      name: Foundation - Set SOC Value Tag
      description: This sends the current metric to the SOC Metrics dataset via an
        HTTP Collector.
      playbookName: Foundation - Set SOC Metric Value Tag
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      Category:
        simple: enrichment
      Tag:
        simple: ask_user_email
      Value:
        simple: "20"
      alertID:
        simple: ${inputs.alertID}
      alertName:
        simple: ${inputs.alertName}
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 30cb72d3-5f51-4f08-8777-ad771ed84d60
    type: title
    task:
      id: 30cb72d3-5f51-4f08-8777-ad771ed84d60
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 450
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 465,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
inputs:
- key: alertID
  value:
    simple: ${alert.id}
  required: true
  description: ""
  playbookInputQuery: null
- key: alertName
  value:
    simple: ${alert.name}
  required: true
  description: ""
  playbookInputQuery: null
inputSections:
- inputs:
  - alertID
  - alertName
  name: General (Inputs group)
  description: Generic group for inputs
outputSections:
- outputs: []
  name: General (Outputs group)
  description: Generic group for outputs
outputs: []
quiet: true
dirtyInputs: true
