adopted: true
contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    isoverridable: false
    itemVersion: 2.0.9
    packID: ""
    packName: SOC Framework
    prevname: ""
    supportedModules: []
    toServerVersion: ""
description: |-
  This playbook is designed to insure ticketing is ready and an instance is configured.  This will pick by they order they are in, so a first match is the ticketing system of choice.
  Currently Supports:
  -- Service Now
  -- Jira
dirtyInputs: true
id: 'SOC Ready Ticketing'
inputSections:
- description: Generic group for inputs
  inputs: []
  name: General (Inputs group)
inputs: []
name: SOC Ready Ticketing
outputSections:
- description: Generic group for outputs
  name: General (Outputs group)
  outputs: []
outputs: []
sourceplaybookid: auto-soc_nist_ir_static-5665921e-797f-469f-a938-801fc03ce4b1
starttaskid: "0"
tags:
- SOC_Framework
- SOC
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "21"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f2d8507e-c7b1-46a3-8716-3084a647eb5c
      iscommand: false
      name: ""
      playbooktaskmissingcomponent: null
      version: -1
    taskid: f2d8507e-c7b1-46a3-8716-3084a647eb5c
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 500,
          "y": 270
        }
      }
  "11":
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8b6dab24-5e99-4dbe-88db-034169678fda
      iscommand: false
      name: Done
      playbooktaskmissingcomponent: null
      type: title
      version: -1
    taskid: 8b6dab24-5e99-4dbe-88db-034169678fda
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 430,
          "y": 1040
        }
      }
  "21":
    continueonerrortype: ""
    id: "21"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "22"
      "yes":
      - "24"
    note: false
    quietmode: 0
    scriptarguments:
      brandname:
        simple: ServiceNow v2
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'.
      id: 467899ed-97d7-413c-9223-4800c7dea4a2
      iscommand: false
      name: Service Now Integration Up?
      playbooktaskmissingcomponent: null
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: 467899ed-97d7-413c-9223-4800c7dea4a2
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 500,
          "y": 440
        }
      }
  "22":
    continueonerrortype: ""
    id: "22"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "no":
      - "25"
      "yes":
      - "23"
    note: false
    quietmode: 0
    scriptarguments:
      brandname:
        simple: Atlassian Jira v3
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Returns 'yes' if integration brand is available. Otherwise returns
        'no'.
      id: c140f091-de39-4990-aff7-404a5a5e0cab
      iscommand: false
      name: Jira Integration Up?
      playbooktaskmissingcomponent: null
      script: IsIntegrationAvailable
      type: condition
      version: -1
    taskid: c140f091-de39-4990-aff7-404a5a5e0cab
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 500,
          "y": 730
        }
      }
  "23":
    continueonerror: true
    continueonerrortype: ""
    id: "23"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: TicketingSystem.Name
      value:
        simple: Atlassian Jira v3
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: f1a3fa68-cda1-4fff-b2e8-69060130392d
      iscommand: false
      name: Set Ticketing System (Jira)
      playbooktaskmissingcomponent: null
      script: Set
      type: regular
      version: -1
    taskid: f1a3fa68-cda1-4fff-b2e8-69060130392d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 120,
          "y": 880
        }
      }
  "24":
    continueonerror: true
    continueonerrortype: ""
    id: "24"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: TicketingSystem.Name
      value:
        simple: ServiceNow v2
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: 5e090dbf-da3d-4519-a68a-4da8393868ee
      iscommand: false
      name: Set Ticketing System (Service Now)
      playbooktaskmissingcomponent: null
      script: Set
      type: regular
      version: -1
    taskid: 5e090dbf-da3d-4519-a68a-4da8393868ee
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 110,
          "y": 590
        }
      }
  "25":
    continueonerror: true
    continueonerrortype: ""
    id: "25"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: TicketingSystem.Name
      value:
        simple: No Ticketing
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: e26fd030-ce1a-49ba-8768-132e744bc308
      iscommand: false
      name: Set Ticketing System (No Ticketing)
      playbooktaskmissingcomponent: null
      script: Set
      type: regular
      version: -1
    taskid: e26fd030-ce1a-49ba-8768-132e744bc308
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 700,
          "y": 880
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 830,
        "width": 970,
        "x": 110,
        "y": 270
      }
    }
  }
